version: '3.8'

services:
  orders-db:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DOCKER_PORT}:${DB_PORT}'

volumes:
  postgres:
    name: ${DOCKER_VOLUME_NAME}
